### ISSUE TITLE
Installer script - chmod error with composer on win7

### ISSUE THREAD

**Issue by koopa** [qcubed/composer#6]
When I tried to install qcubed beta-3, composer aborted due to a chmod error and the error has been tracked down to this:

e7b81cfae09ffcd8930c88420d0bfaa7edf330d7

Let me know whether the changes should be merged or there is a better solution to this.

**Comment by spekary** [comment]
Yes, please submit a merge request.

**Comment by koopa** [comment]
Request sent.
